version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hackujstat-frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      # - NEXT_PUBLIC_API_URL=http://localhost:8000/api # Případná vrchní ukázka pro backend
