networks:
  what-now-network:
    name: what-now-network
    driver: bridge

services:
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: frontend
  #   ports:
  #     - "3000:3000"
  #   restart: unless-stopped
  #   # environment:
  #   # NODE_ENV: production
  #   # NEXT_PUBLIC_API_URL: http://localhost:8000/api # Případná vrchní ukázka pro backend
  #   networks:
  #     - what-now-network

  backend:
    image: backend:latest
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: no
    env_file:
      - .env

    environment:
      HF_TOKEN: ${HF_TOKEN}
      HF_HUB_DISABLE_XET: "1"
      HF_HOME: /root/.cache/huggingface

    ports:
      - "${API_PORT}:${API_PORT}"

    volumes:
      - ./backend/src/:/app/src/
      - ./backend/main.py:/app/main.py
      - ./backend/alembic.ini:/app/alembic.ini
      - ./backend/migrations/:/app/migrations/
      - huggingface-cache:/root/.cache/huggingface

    networks:
      - what-now-network

    depends_on:
      backend-db:
        condition: service_healthy

  backend-db:
    image: pgvector/pgvector:0.6.0-pg16
    container_name: backend-db
    restart: no
    env_file:
      - .env

    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --username=${POSTGRES_USER} --dbname=${POSTGRES_DB}" ]
      interval: 5s
      timeout: 3s
      retries: 5

    networks:
      - what-now-network
  # beat:
  #   build:
  #     context: ./tasks
  #     dockerfile: Dockerfile
  #   container_name: parser_beat
  #   command: celery -A src.celery.app beat -l info
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./tasks/src/:/app/src/
  #     - ./tasks/main.py:/app/main.py

  #   depends_on:
  #     rabbitmq:
  #       condition: service_started
  # worker:
  #   build:
  #     context: ./tasks
  #     dockerfile: Dockerfile
  #   container_name: parser_worker
  #   command: celery -A src.celery.app worker -l info
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./tasks/src/:/app/src/
  #     - ./tasks/main.py:/app/main.py
  #   depends_on:
  #     rabbitmq:
  #       condition: service_started

  # rabbitmq:
  #   image: rabbitmq:3.13-management
  #   container_name: rabbitmq
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   environment:
  #     RABBITMQ_DEFAULT_USER: guest
  #     RABBITMQ_DEFAULT_PASS: guest
  #   volumes:
  #     - rabbitmq-data:/var/lib/rabbitmq/data

volumes:
  rabbitmq-data:
  huggingface-cache:
