name: application

networks:
  project-network:
    name: project-network
    driver: bridge

services:
  backend:
    image: backend:latest
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: no
    env_file:
      - .env

    ports:
      - "8001:8001"

    volumes:
      - ./src/:/app/src/
      - ./main.py:/app/main.py
      - ./alembic.ini:/app/alembic.ini
      - ./migrations/:/app/migrations/
    networks:
      - project-network

    depends_on:
      backend-db:
        condition: service_healthy

  backend-db:
    image: postgres:16-alpine
    container_name: backend-db
    restart: no
    env_file:
      - .env

    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --username=backend --dbname=hackujstat" ]
      interval: 5s
      timeout: 3s
      retries: 5

    networks:
      - project-network
