"""initial_structure

Revision ID: 114d575818bc
Revises:
Create Date: 2026-05-06 10:54:39.704627

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy as pgv

# revision identifiers, used by Alembic.
revision: str = "114d575818bc"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Install pgvector extension first
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lawchunk",
        sa.Column("document_number", sa.String(length=100), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("fragment_id", sa.Integer(), nullable=False),
        sa.Column("depth", sa.Integer(), nullable=False),
        sa.Column("fragment_type", sa.String(length=50), nullable=False),
        sa.Column("clean_text", sa.Text(), nullable=True),
        sa.Column("embedding", pgv.vector.VECTOR(dim=1536), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_lawchunk_document_number"),
        "lawchunk",
        ["document_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lawchunk_fragment_id"), "lawchunk", ["fragment_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_lawchunk_fragment_id"), table_name="lawchunk")
    op.drop_index(op.f("ix_lawchunk_document_number"), table_name="lawchunk")
    op.drop_table("lawchunk")

    # Drop pgvector extension
    op.execute("DROP EXTENSION IF NOT EXISTS vector")
    # ### end Alembic commands ###
