"""update law_chunk model to support pdf files

Revision ID: 3a9ef919504b
Revises: 4d520d6d9506
Create Date: 2026-05-10 16:30:08.952314

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3a9ef919504b"
down_revision: Union[str, Sequence[str], None] = "4d520d6d9506"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "lawchunk", sa.Column("source_kind", sa.String(length=20), nullable=False)
    )
    op.add_column("lawchunk", sa.Column("page_start", sa.Integer(), nullable=True))
    op.add_column("lawchunk", sa.Column("page_end", sa.Integer(), nullable=True))
    op.add_column("lawchunk", sa.Column("chunk_index", sa.Integer(), nullable=True))
    op.add_column(
        "lawchunk", sa.Column("section_title", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "lawchunk", sa.Column("source_filename", sa.String(length=255), nullable=True)
    )
    op.alter_column(
        "lawchunk", "fragment_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column("lawchunk", "depth", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "lawchunk", "fragment_type", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    op.create_index(
        op.f("ix_lawchunk_chunk_index"), "lawchunk", ["chunk_index"], unique=False
    )
    op.create_index(
        op.f("ix_lawchunk_source_kind"), "lawchunk", ["source_kind"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_lawchunk_source_kind"), table_name="lawchunk")
    op.drop_index(op.f("ix_lawchunk_chunk_index"), table_name="lawchunk")
    op.alter_column(
        "lawchunk", "fragment_type", existing_type=sa.VARCHAR(length=50), nullable=False
    )
    op.alter_column("lawchunk", "depth", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "lawchunk", "fragment_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_column("lawchunk", "source_filename")
    op.drop_column("lawchunk", "section_title")
    op.drop_column("lawchunk", "chunk_index")
    op.drop_column("lawchunk", "page_end")
    op.drop_column("lawchunk", "page_start")
    op.drop_column("lawchunk", "source_kind")
    # ### end Alembic commands ###
