"""update vector dimension

Revision ID: 4d520d6d9506
Revises: 114d575818bc
Create Date: 2026-05-10 13:07:34.774683

"""

from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy as pgv  # type: ignore

# revision identifiers, used by Alembic.
revision: str = "4d520d6d9506"
down_revision: Union[str, Sequence[str], None] = "114d575818bc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "lawchunk",
        "embedding",
        existing_type=pgv.VECTOR(dim=1536),
        type_=pgv.VECTOR(dim=768),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "lawchunk",
        "embedding",
        existing_type=pgv.VECTOR(dim=768),
        type_=pgv.VECTOR(dim=1536),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
