"""initial structure

Revision ID: 84bde0775bee
Revises:
Create Date: 2026-05-13 12:24:42.398891

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy as pgv  # type: ignore


# revision identifiers, used by Alembic.
revision: str = "84bde0775bee"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lawchunk",
        sa.Column("document_number", sa.String(length=100), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("source_kind", sa.String(length=20), nullable=False),
        sa.Column("fragment_id", sa.Integer(), nullable=True),
        sa.Column("depth", sa.Integer(), nullable=True),
        sa.Column("fragment_type", sa.String(length=50), nullable=True),
        sa.Column("page_start", sa.Integer(), nullable=True),
        sa.Column("page_end", sa.Integer(), nullable=True),
        sa.Column("chunk_index", sa.Integer(), nullable=True),
        sa.Column("section_title", sa.String(length=255), nullable=True),
        sa.Column("source_filename", sa.String(length=255), nullable=True),
        sa.Column("clean_text", sa.Text(), nullable=True),
        sa.Column("embedding", pgv.vector.VECTOR(dim=768), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_lawchunk_chunk_index"), "lawchunk", ["chunk_index"], unique=False
    )
    op.create_index(
        op.f("ix_lawchunk_document_number"),
        "lawchunk",
        ["document_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lawchunk_fragment_id"), "lawchunk", ["fragment_id"], unique=True
    )
    op.create_index(
        op.f("ix_lawchunk_source_kind"), "lawchunk", ["source_kind"], unique=False
    )
    op.create_table(
        "socialservice",
        sa.Column("source_service_id", sa.Integer(), nullable=False),
        sa.Column("identifier", sa.String(length=32), nullable=False),
        sa.Column("provider_id", sa.Integer(), nullable=False),
        sa.Column("provider_name", sa.String(length=255), nullable=False),
        sa.Column("provider_ico", sa.String(length=32), nullable=True),
        sa.Column("service_type_id", sa.Integer(), nullable=False),
        sa.Column("active_from", sa.Date(), nullable=False),
        sa.Column("active_to", sa.Date(), nullable=True),
        sa.Column("region_scope_by_address", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_socialservice_identifier"),
        "socialservice",
        ["identifier"],
        unique=False,
    )
    op.create_index(
        op.f("ix_socialservice_provider_id"),
        "socialservice",
        ["provider_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_socialservice_service_type_id"),
        "socialservice",
        ["service_type_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_socialservice_source_service_id"),
        "socialservice",
        ["source_service_id"],
        unique=True,
    )
    op.create_table(
        "servicelocation",
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.Column("provider_id", sa.Integer(), nullable=False),
        sa.Column("street", sa.String(length=255), nullable=True),
        sa.Column("number", sa.String(length=64), nullable=True),
        sa.Column("district", sa.String(length=255), nullable=True),
        sa.Column("municipality", sa.String(length=255), nullable=True),
        sa.Column("postal_code", sa.String(length=16), nullable=True),
        sa.Column("region", sa.String(length=255), nullable=True),
        sa.Column("service_name", sa.String(length=255), nullable=True),
        sa.Column("lat", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("lon", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["service_id"], ["socialservice.source_service_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_service_locations_municipality",
        "servicelocation",
        ["municipality"],
        unique=False,
    )
    op.create_index(
        "ix_service_locations_provider_id",
        "servicelocation",
        ["provider_id"],
        unique=False,
    )
    op.create_index(
        "ix_service_locations_region", "servicelocation", ["region"], unique=False
    )
    op.create_index(
        "ix_service_locations_service_name",
        "servicelocation",
        ["service_name"],
        unique=False,
    )
    op.create_table(
        "servicetargetgroup",
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.Column("source_group_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["service_id"], ["socialservice.source_service_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_service_target_groups_service_id",
        "servicetargetgroup",
        ["service_id"],
        unique=False,
    )
    op.create_index(
        "ix_service_target_groups_source_group_id",
        "servicetargetgroup",
        ["source_group_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP EXTENSION IF EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_service_target_groups_source_group_id", table_name="servicetargetgroup"
    )
    op.drop_index(
        "ix_service_target_groups_service_id", table_name="servicetargetgroup"
    )
    op.drop_table("servicetargetgroup")
    op.drop_index("ix_service_locations_service_name", table_name="servicelocation")
    op.drop_index("ix_service_locations_region", table_name="servicelocation")
    op.drop_index("ix_service_locations_provider_id", table_name="servicelocation")
    op.drop_index("ix_service_locations_municipality", table_name="servicelocation")
    op.drop_table("servicelocation")
    op.drop_index(
        op.f("ix_socialservice_source_service_id"), table_name="socialservice"
    )
    op.drop_index(op.f("ix_socialservice_service_type_id"), table_name="socialservice")
    op.drop_index(op.f("ix_socialservice_provider_id"), table_name="socialservice")
    op.drop_index(op.f("ix_socialservice_identifier"), table_name="socialservice")
    op.drop_table("socialservice")
    op.drop_index(op.f("ix_lawchunk_source_kind"), table_name="lawchunk")
    op.drop_index(op.f("ix_lawchunk_fragment_id"), table_name="lawchunk")
    op.drop_index(op.f("ix_lawchunk_document_number"), table_name="lawchunk")
    op.drop_index(op.f("ix_lawchunk_chunk_index"), table_name="lawchunk")
    op.drop_table("lawchunk")
    # ### end Alembic commands ###
