"""update service target group model

Revision ID: ddb3cbf656ba
Revises: 84bde0775bee
Create Date: 2026-05-13 13:14:47.332876

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy as pgv  # type: ignore


# revision identifiers, used by Alembic.
revision: str = "ddb3cbf656ba"
down_revision: Union[str, Sequence[str], None] = "84bde0775bee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "servicetargetgroup",
        sa.Column("embedding", pgv.vector.VECTOR(dim=768), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("servicetargetgroup", "embedding")
    # ### end Alembic commands ###
