"""add service models

Revision ID: ef906874e646
Revises: 3a9ef919504b
Create Date: 2026-05-12 18:32:21.428733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef906874e646'
down_revision: Union[str, Sequence[str], None] = '3a9ef919504b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('socialservice',
    sa.Column('source_service_id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=32), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(length=255), nullable=False),
    sa.Column('provider_ico', sa.String(length=32), nullable=True),
    sa.Column('service_type_id', sa.Integer(), nullable=False),
    sa.Column('active_from', sa.Date(), nullable=False),
    sa.Column('active_to', sa.Date(), nullable=True),
    sa.Column('region_scope_by_address', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_socialservice_identifier'), 'socialservice', ['identifier'], unique=False)
    op.create_index(op.f('ix_socialservice_provider_id'), 'socialservice', ['provider_id'], unique=False)
    op.create_index(op.f('ix_socialservice_service_type_id'), 'socialservice', ['service_type_id'], unique=False)
    op.create_index(op.f('ix_socialservice_source_service_id'), 'socialservice', ['source_service_id'], unique=True)
    op.create_table('service_locations',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('street', sa.String(length=255), nullable=True),
    sa.Column('number', sa.String(length=64), nullable=True),
    sa.Column('district', sa.String(length=255), nullable=True),
    sa.Column('municipality', sa.String(length=255), nullable=True),
    sa.Column('postal_code', sa.String(length=16), nullable=True),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('service_name', sa.String(length=255), nullable=True),
    sa.Column('lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('lon', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['socialservice.source_service_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_service_locations_municipality', 'service_locations', ['municipality'], unique=False)
    op.create_index('ix_service_locations_provider_id', 'service_locations', ['provider_id'], unique=False)
    op.create_index('ix_service_locations_region', 'service_locations', ['region'], unique=False)
    op.create_index('ix_service_locations_service_name', 'service_locations', ['service_name'], unique=False)
    op.create_table('servicetargetgroup',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('source_group_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['socialservice.source_service_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_service_target_groups_service_id', 'servicetargetgroup', ['service_id'], unique=False)
    op.create_index('ix_service_target_groups_source_group_id', 'servicetargetgroup', ['source_group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_service_target_groups_source_group_id', table_name='servicetargetgroup')
    op.drop_index('ix_service_target_groups_service_id', table_name='servicetargetgroup')
    op.drop_table('servicetargetgroup')
    op.drop_index('ix_service_locations_service_name', table_name='service_locations')
    op.drop_index('ix_service_locations_region', table_name='service_locations')
    op.drop_index('ix_service_locations_provider_id', table_name='service_locations')
    op.drop_index('ix_service_locations_municipality', table_name='service_locations')
    op.drop_table('service_locations')
    op.drop_index(op.f('ix_socialservice_source_service_id'), table_name='socialservice')
    op.drop_index(op.f('ix_socialservice_service_type_id'), table_name='socialservice')
    op.drop_index(op.f('ix_socialservice_provider_id'), table_name='socialservice')
    op.drop_index(op.f('ix_socialservice_identifier'), table_name='socialservice')
    op.drop_table('socialservice')
    # ### end Alembic commands ###
